### ISSUE TITLE
Update to Flarum Beta 16

### ISSUE THREAD

**Issue by cindy-koijam** [dartrax/flarum-wp-avatar-privacy#2]
Hi!
Are you planning on updating this plugin to the new Beta 16 version of Flarum?

**Comment by dartrax** [comment]
Hi @cindy-koijam, sorry for my late answer. I didn't seem to have configured the notifications properly.
I omitted beta 16 in favor of the first stable release of flarum. I've just updated the plugin to work with v1.0. Please let me know if there are any issues.
